name: CI

on:
  push:
    branches:
      - main
      - develop
      - staging
      - prod
      - 'feature/**'
  pull_request:
    branches:
      - main
      - develop
      - staging
      - prod

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install pnpm using npm and update PATH
        run: |
          npm install -g pnpm@10.11.1

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run tests
        run: pnpm test

      # - name: Run linter
      #   run: pnpm lint

      # The following steps are only for future CI/CD on main, develop, staging, prod (not feature branches):
      # - name: Build packages
      #   run: pnpm build
      # - name: Publish to npm
      #   run: pnpm publish
      # - name: Deploy to production
      #   run: <deployment-script> 